name: HetznerMount
options:
  bundleIdPrefix: com.hetzner.mount
  deploymentTarget:
    macOS: "14.0"
  groupSortPosition: top
  generateEmptyDirectories: true

packages:
  HetznerMountKit:
    path: Packages/HetznerMountKit

targets:
  HetznerMount:
    type: application
    platform: macOS
    sources:
      - path: HetznerMount
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hetzner.mount.app
        PRODUCT_NAME: HetznerMount
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        SWIFT_VERSION: "5.9"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        INFOPLIST_FILE: HetznerMount/Info.plist
        CODE_SIGN_ENTITLEMENTS: HetznerMount/HetznerMount.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: HetznerMountKit
      - target: FileProviderExtension
        embed: true
        codeSign: true

  FileProviderExtension:
    type: app-extension
    platform: macOS
    sources:
      - path: FileProviderExtension
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hetzner.mount.app.fileprovider
        PRODUCT_NAME: FileProviderExtension
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        SWIFT_VERSION: "5.9"
        SKIP_INSTALL: YES
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        INFOPLIST_FILE: FileProviderExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: FileProviderExtension/FileProviderExtension.entitlements
    dependencies:
      - package: HetznerMountKit

schemes:
  HetznerMount:
    build:
      targets:
        HetznerMount: all
        FileProviderExtension: all
    run:
      config: Debug
